<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title></title>
</head>
<body>
	<!--contact-->
<div class="terms">
	<div class="container">
		<h3>Terms and Conditions <br>for Merchants for membership applications  </h3><br>
		<h4>Agreement between Users and EverOffer</h4>
		<p>Global Creation Services private limited provides online platform for offline, all kind of purchase and it is providing facility for merchants to show their offers and advertisement of their product, shop and services. (collectively, the "Services"), which Services are accessible at www.everoffer.in and any other websites through which 'everoffer' makes the Services available (collectively, the "Site") and as an application for mobile devices (the "Application"). By using the Site and Application, you agree to comply with and be legally bound by the terms and conditions of these Terms of Service ("Terms"), whether or not you become a registered user of the Services. These Terms govern your access to and use of the Site, Application and Services and all Collective Content (defined below), and your participation in the Referral Program (defined below), and constitute a binding legal agreement between you and everoffer. Please read carefully these Terms and our Privacy Policy, which may be found at http://www.everoffer.in/terms, and which is incorporated by reference into these Terms. If you do not agree to these Terms, you have no right to obtain information from or otherwise continue using the Site or Application. Failure to use the Site and Application in accordance with these Terms may subject you to civil and criminal penalties.</p>
        
        <p>THE SITE, APPLICATION AND SERVICES COMPRISE AN ONLINE PLATFORM THROUGH WHICH MERCHANT (DEFINED BELOW) MAY CREATE LISTINGS (DEFINED BELOW) FOR OFFERS (DEFINED BELOW) AND COUSTOMER (DEFINED BELOW) AND MERCHANT (DEFINED BELOW) MAY LEARN ABOUT AND OFFERS ON THE PRODUCT AND SERVICES. YOU UNDERSTAND AND AGREE THAT EVEROFFER IS NOT A PARTY TO ANY AGREEMENTS ENTERED INTO BETWEEN COUSTOMERS AND MERCHANTS, NOR IS EVEROFFER A REAL ESTATE BROKER, AGENT OR INSURER. EVEROFFER HAS NO CONTROL OVER THE CONDUCT OF COUSTOMER, MERCHANT AND OTHER USERS OF THE SITE, APPLICATION AND SERVICES OR ANY PROUDUCTS AND DISCLAIMS ALL LIABILITY IN THIS REGARD.</p>
        <br>
		<h4>Key Terms</h4>
		<p>EVEROFFER Content means all Content that EVEROFFER makes available through the Site, Application, or Services, including any Content licensed from a third party, but excluding Member Content.</p>
		<p>Collective Content means Member Content and EVEROFFER Content.</p>
		
		<p>Content means text, graphics, images, music, software (excluding the Application), audio, video, information or other materials.</p>
        <p>Customer means a Member who downloads the our application or use our site  and request for code or discount coupons for his or her purchese of product or request for use the service. </p>
        
<p>Listing means OFFERS that is listed by a Merchant as available on website or application through our agent of their own login system. </p>
<p>Member means a person who completes EVEROFFER's account registration process, including, but not limited to costumers and Merchants, as described under "Account Registration" below.</p>
<p>Merchant's offer Content means all Content that a Merchant posts, uploads, publishes, submits or transmits to be made available through the Site, Application or Services.</p>

<p>Tax or "Taxes" mean any sales taxes, value added taxes (VAT), goods and services taxes (GST) and other similar municipal, state and national indirect or other withholding and personal or corporate income taxes.
</p>
<p>Certain areas of the Site and Application (and your access to or use of certain aspects of the Services or Collective Content) may have different terms and conditions posted or may require you to agree with and accept additional terms and conditions. If there is a conflict between these Terms and terms and conditions posted for a specific area of the Site, Application, Services, or Collective Content, the latter terms and conditions will take precedence with respect to your use of or access to that area of the Site, Application, Services, or Collective Content.</p>

<p>YOU ACKNOWLEDGE AND AGREE THAT, BY ACCESSING OR USING THE SITE, APPLICATION OR SERVICES OR BY DOWNLOADING OR POSTING ANY CONTENT FROM OR ON THE SITE, VIA THE APPLICATION OR THROUGH THE SERVICES, OR BY PARTICIPATING IN THE REFERRAL PROGRAM, YOU ARE INDICATING THAT YOU HAVE READ, AND THAT YOU UNDERSTAND AND AGREE TO BE BOUND BY THESE TERMS, WHETHER OR NOT YOU HAVE REGISTERED WITH THE SITE AND APPLICATION. IF YOU DO NOT AGREE TO THESE TERMS, THEN YOU HAVE NO RIGHT TO ACCESS OR USE THE SITE, APPLICATION, SERVICES, OR COLLECTIVE CONTENT OR TO PARTICIPATE IN THE REFERRAL PROGRAM.</p>


<p>If you accept or agree to these Terms on behalf of a company or other legal entity, you represent and warrant that you have the authority to bind that company or other legal entity to these Terms and, in such event, "you" and "your" will refer and apply to that company or other legal entity.</p>
<br>
<h4>Modification</h4>
<p>EVEROFFER reserves the right, at its sole discretion, to modify the Site, Application or Services or to modify these Terms, including the Service Fees, at any time and without prior notice. If we modify these Terms, we will post the modification on the Site or via the Application or provide you with notice of the modification. We will also update the "Last Updated Date" at the top of these Terms. By continuing to access or use the Site, Application or Services after we have posted a modification on the Site or via the Application or have provided you with notice of a modification, you are indicating that you agree to be bound by the modified Terms. If the modified Terms are not acceptable to you, your only recourse is to cease using the Site, Application and Services.</p>
<br>
<h4>Eligibility</h4>
<p>The Site, Application and Services are intended solely for persons who are 18 or older. Any access to or use of the Site, Application or Services by anyone under 18 is expressly prohibited. By accessing or using the Site, Application or Services you represent and warrant that you are 18 or older.</p>
<br>
<h4>How the Site, Application and Services Work</h4>
<p>The Site, Application and Services can be used to facilitate the listing THE OFFERS BY MERCHANT and DISCOUNT COUPANS FOR COUSTOMERS Such OFFERS are included in Listings on the Site, Application and Services by MERCHANTS. You may view Listings as an unregistered visitor to the Site, Application and Services; however, if you wish to book an Accommodation or create a Listing, you must first register to create an EVEROFFER Account (defined below).</p>

<p>As stated above, EVEROFFER makes available a platform or marketplace with related technology for COSTOMERS and MERCHANTS to meet online and arrange for different offers for their punches of product and services provided by merchants through everoffer coupons. EVEROFFER is not an owner or operator of properties, including, but not limited to, hotel rooms, motel rooms, other lodgings or Accommodations, all kind of shops, all kind of services sectors nor is it a provider of properties, including, but not limited to, hotel rooms, motel rooms, other lodgings or Accommodations and shops and services and everoffer  does not own, sell, resell, furnish, provide, rent, re-rent, manage and/or control properties and services, including, but not limited to, hotel rooms, motel rooms, other lodgings or Accommodations, shops, shores and services or transportation or travel services and EVEROFFER's role is solely to facilitate the availability of the Site, Application and Services. Similarly, EVEROFFER is not a contracting agent or representative of any merchant. Instead, EVEROFFER's role is solely to facilitate the availability of the Site, Application and Services for Members and to provide services related thereto.</p>

<p>PLEASE NOTE THAT, AS STATED ABOVE, THE SITE, APPLICATION AND SERVICES ARE INTENTED TO BE USED TO FACILIATE THE DISCOUNT OR OFFERS OF PRODUCT OR SERVICES BY MERCHANT AND SERVICE PROVIDER. EVEROFFER CANNOT AND DOES NOT CONTROL THE CONTENT CONTAINED IN ANY LISTINGS AND THE CONDITION, LEGALITY OR SUITABILITY OF ANY PRODUCT OT SERVICES. EVEROFFER IS NOT RESPONSIBLE FOR AND DISCLAIMS ANY AND ALL LIABILITY RELATED TO ANY AND ALL LISTINGS AND OFFER COUPANS. ACCORDINGLY, ANY PURCHES WILL BE MADE AT THE COUSTOMERS'S OWN RISK.</p>
<br>
<h4>Account Registration</h4>
<p>In order to access certain features of the Site and Application, and to book an Accommodation or create a Listing, you must register to create an account ("EVEROFFER Account") and become a Member. You may register to join the Services directly via the Site or Application or as described in this section.</p>

<p>You can also register to join by logging into your account with certain third party social networking sites ("SNS") (including, but not limited to, Facebook); each such account, a "Third Party Account", via our Site or Application, as described below. As part of the functionality of the Site, Application and Services, you may link your EVEROFFER Account with Third Party Accounts, by either: (i) providing your Third Party Account login information to   </p>


<p>EVEROFFER through the Site, Services or Application; or (ii) allowing EVEROFFER to access your Third Party Account, as is permitted under the applicable terms and conditions that govern your use of each Third Party Account. You represent that you are entitled to disclose your Third Party Account login information to EVEROFFER and/or grant EVEROFFER access to your Third Party Account (including, but not limited to, for use for the purposes described herein), without breach by you of any of the terms and conditions that govern your use of the applicable Third Party Account and without obligating EVEROFFER to pay any fees or making EVEROFFER subject to any usage limitations imposed by such third party service providers. By granting EVEROFFER access to any Third Party Accounts, you understand that EVEROFFER will access, make available and store (if applicable) any Content that you have provided to and stored in your Third Party Account ("SNS Content") so that it is available on and through the Site, Services and Application via your EVEROFFER Account and EVEROFFER Account profile page. Unless otherwise specified in these Terms, all SNS Content, if any, shall be considered to be Member Content for all purposes of these Terms. Depending on the Third Party Accounts you choose and subject to the privacy settings that you have set in such Third Party Accounts, personally identifiable information that you post to your Third Party Accounts will be available on and through your EVEROFFER Account on the Site, Services and Application. Please note that if a Third Party Account or associated service becomes unavailable or EVEROFFER's access to such Third Party Account is terminated by the third party service provider, then SNS Content will no longer be available on and through the Site, Services and Application. You have the ability to disable the connection between your EVEROFFER Account and your Third Party Accounts, at any time, by accessing the "Settings" section of the Site and Application.</p>
<br>

<p>PLEASE NOTE THAT YOUR RELATIONSHIP WITH THE THIRD PARTY SERVICE PROVIDERS ASSOCIATED WTH YOUR THIRD PARTY ACCOUNTS IS GOVERNED SOLELY BY YOUR AGREEMENT(S) WITH SUCH THIRD PARTY SERVICE PROVIDERS. EVEROFFER makes no effort to review any SNS Content for any purpose, including but not limited to, for accuracy, legality or non-infringement and EVEROFFER is not responsible for any SNS Content.</p>



<p>We will create your EVEROFFER Account and your EVEROFFER Account profile page for your use of the Site and Application based upon the personal information you provide to us or that we obtain via an SNS as described above. You may not have more than one (1) active EVEROFFER Account. </p>


<p>You agree to provide accurate, current and complete information during the registration process and to update such information to keep it accurate, current and complete. EVEROFFER reserves the right to suspend or terminate your EVEROFFER Account and your access to the Site, Application and Services if you create more than one (1) EVEROFFER Account or if any information provided during the registration process or thereafter proves to be inaccurate, not current or incomplete. You are responsible for safeguarding your password. You agree that you will not disclose your password to any third party and that you will take sole responsibility for any activities or actions under your EVEROFFER Account, whether or not you have authorized such activities or actions. You will immediately notify EVEROFFER of any unauthorized use of your EVEROFFER Account.</p>
<br>
<h4>Accommodation Listings</h4>
<p>As a Member, you may create Listings. To this end, you will be asked a variety of questions about the PRODUCT PURCHES OR SERVICE USED to be listed, including, but not limited to, the location, capacity, size, features, availability of the PRODUCT PURCHES OR SERVICE USED and pricing and related rules and financial terms. In order to be featured in Listings via the Site, Application and Services, all PRODUCT PURCHES OR SERVICE USED must have valid physical addresses. Listings will be made publicly available via the Site, Application and Services. Other Members will be able to use discount coupons created via the Site, Application and Services based upon the information provided in your Listing. You understand and agree that once customers' requests discount coupons for avail facility of discount for their purchase of product or services.  </p>

<p>You acknowledge and agree that you are solely responsible for any and all Listings you post. Accordingly, you represent and warrant that any Listing you post and customers at, an offer in a Listing you post (i) will not breach any agreements you have entered into with any third parties and (ii) will (a) be in compliance with all applicable laws, Tax requirements, and rules and regulations that may apply to any punches and avail service included in a Listing you post, including, but not limited to, zoning laws and laws governing rentals of residential and other properties and (b) not conflict with the rights of third parties. Please note that EVEROFFER assumes no responsibility for Customer's compliance with any applicable laws, rules and regulations.</p>


<p>You understand and agree that EVEROFFER does not act as an insurer or as a contracting agent for, or representative of, you as a Merchant and if a customer requests a discount coupon of your purchase or availing services, any agreement you enter into with such Merchant is between you and the Customer and EVEROFFER is not a party thereto. Please note that EVEROFFER reserves the right, at any time and without prior notice, to remove or disable access to any Listing for any reason, including Listings that EVEROFFER, in its sole discretion, considers to be objectionable for any reason, in violation of these Terms or otherwise harmful to the Site, Application or Services.</p>

<p>When you create a Listing, you may also choose to include certain requirements which must be met by the Members who are eligible to request a discount coupan, including, but not limited to, requiring Members to have a profile picture or verified phone number, in order to avail discount coupan. Any Member wishing to avail discount coupon included in Listings with such requirements must meet these requirements. More information on how to set such requirements is available via the "Merchant login" section of the Site, Application and Services.</p>

<p>If you are a Merchant, EVEROFFER makes certain tools available to you to help you to make informed decisions about which Members you choose to confirm for Availing discount booking for your Accommodation. You acknowledge and agree that, as a Merchant, you are responsible for your own acts and omissions and are also responsible for the acts and omissions of any individuals who reside at or are otherwise present during creation of discount coupons or any other listing. or invitation, excluding the Customer(and the individuals the Customer invites to the Accommodation, if applicable.)</p>


<p>EVEROFFER recommends that Merchant obtain appropriate insurance for their stores and shops. Please review any insurance policy that you may have for your stores and shops or business perpose carefully, and in particular please make sure that you are familiar with and understand any exclusions to, and any deductibles that may apply for, such insurance policy, including, but not limited to, whether or not your insurance policy will cover the actions or inactions of Customers (and the individuals the Customers invites to the stores, shops and services if applicable) while at your stores, shops.</p>
<br>
<h4>Headings</h4>
<p>The headings and subheadings herein are included for convenience and identification only and are not intended to describe, interpret, define or limit the scope, extent or intent of this agreement, terms and conditions, notices, or the right to use this website by the User contained herein or any other section or pages of EVEROFFER Websites or its partner websites or any provision hereof in any manner whatsoever.

In the event that any of the terms, conditions, and notices contained herein conflict with the Additional Terms or other terms and guidelines contained within any particular EVEROFFER website, then these terms shall control.
</p>
<br>
<h4>No Endorsement</h4>
<p>EVEROFFER does not endorse any Members or any SHOPS AND STORES OR SERVICE PROVIDER. In addition, although these Terms require Members to provide accurate information, we do not attempt to confirm, and do not confirm, any Member's purported identity. You are responsible for determining the identity and suitability of others who you contact via the Site, Application and Services. Except as provided in the EVEROFFER Customers Guarantee Terms and Conditions ("EVEROFFER Merchant Guarantee"), which is an agreement between EVEROFFER and Merchant, we will not be responsible for any damage or harm resulting from your interactions with other Members. (Please see EVEROFFER's Merchant Guarantee Terms and Conditions at www.everoffer.in /terms for information about the EVEROFFER Merchant Host Guarantee.) By using the Site, Application or Services, you agree that any legal remedy or liability that you seek to obtain for actions or omissions of other Members or other third parties will be limited to a claim against the particular Members or other third parties who caused you harm and you agree not to attempt to impose liability on, or seek any legal remedy from EVEROFFER with respect to such actions or omissions. Accordingly, we encourage you to communicate directly with other Members on the Site and Services regarding any bookings or Listings made by you.</p>
<br>
<h4>Service Fees</h4>
<p>In consideration for providing the Services, EVEROFFER collects service fees from Merchant ("Subscription Fees"). Merchants who are EVEROFFER members have to pay subscription charges as per given in the list of fees. Merchant have to pay ONLY with 'on line secured payment gateway' of Global Creation Services Private Limited. EVEROFFER is not responsible for any other payment except 'through online payment gateway'. The fees are divided for different categories of business and services for uploading offers facilities. You are completely responsible of any offline payment; everoffer is not asking any of it's representative for collection of Money. We don't have any collection agents. Once the money you paid is exhausted from you everoffer account then you have to refill your account. We recommended changing your offers regularly and once you change your offer, you cannot change it for at least 7 days.</p>

<br>
<h4>Links</h4>
<p>The Site, Application and Services may contain links to third-party websites or resources. You acknowledge and agree that everoffer is not responsible or liable for: (i) the availability or accuracy of such websites or resources; or (ii) the content, products, or services on or available from such websites or resources. Links to such websites or resources do not imply any endorsement by EVEROFFER of such websites or resources or the content, products, or services available from such websites or resources. You acknowledge sole responsibility for and assume all risk arising from your use of any such websites or resources or the Content, products or services on or available from such websites or resources.</p>
<br>
<h4>Proprietary Rights Notices</h4>
<p>All trademarks, service marks, logos, trade names and any other proprietary designations of EVEROFFER used herein are trademarks or registered trademarks of EVEROFFER. Any other trademarks, service marks, logos, trade names and any other proprietary designations are the trademarks or registered trademarks of their respective parties.</p>
<br>
<h4>Feedback</h4>
<p>We welcome and encourage you to provide feedback, comments and suggestions for improvements to the Site, Application and Services ("Feedback"). You may submit Feedback by emailing us at info@everoffer or through the Contact (www.everoffer.in/contact) section of the Site and Application. You acknowledge and agree that all Feedback will be the sole and exclusive property of EVEROFFER and you hereby irrevocably assign to EVEROFFER and agree to irrevocably assign to EVEROFFER all of your right, title, and interest in and to all Feedback, including without limitation all worldwide patent, copyright, trade secret, moral and other proprietary or intellectual property rights therein. At EVEROFFER's request and expense, you will execute documents and take such further acts as EVEROFFER may reasonably request to assist EVEROFFER to acquire, perfect, and maintain its intellectual property rights and other legal protections for the Feedback.</p>
<br>
<h4>Copyright Policy</h4>
<p>EVEROFFER respects copyright law and expects its users to do the same. It is EVEROFFER's policy to terminate in appropriate circumstances the EVEROFFER Accounts of Members or other account holders who repeatedly infringe or are believed to be repeatedly infringing the rights of copyright holders. Please see EVEROFFER's Copyright Policy at www.everoffer.in/terms for further information.</p>
<br>
<h4>Termination and Everoffer Account Cancellation</h4>
<p>We may, in our discretion and without liability to you, with or without cause, with or without prior notice and at any time: (a) terminate these Terms or your access to our Site, Application and Services, and (b) deactivate or cancel your EVEROFFER Account. Upon termination we will promptly pay you any amounts we reasonably determine we owe you in our discretion, which we are legally obligated to pay you. In the event EVEROFFER terminates these Terms, or your access to our Site, Application and Services or deactivates or cancels your EVEROFFER Account you will remain liable for all amounts due hereunder. You may cancel your EVEROFFER Account at any time via the "Cancel Account" feature of the Services or by sending an email to hr@everoffer.in.  Please note that if your EVEROFFER Account is cancelled, we do not have an obligation to delete or return to you any content you have posted to the Site, Application and Services, including, but not limited to, any reviews or Feedback.</p>
<br>
<h4>Disclaimers</h4>
<p>IF YOU CHOOSE TO USE THE SITE, APPLICATION, SERVICES AND PARTICIPATE IN THE REFERRAL PROGRAM, YOU DO SO AT YOUR SOLE RISK. YOU ACKNOWLEDGE AND AGREE THAT EVEROFFER DOES NOT CONDUCT BACKGROUND CHECKS ON ANY MEMBER, INCLUDING, BUT NOT LIMITED TO, COUSTOMERS AND MERCHANTS. THE SITE, APPLICATION, SERVICES, COLLECTIVE CONTENT AND REFERRAL PROGRAM ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED. WITHOUT LIMITING THE FOREGOING, EVEROFFER EXPLICITLY DISCLAIMS ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. EVEROFFER MAKES NO WARRANTY THAT THE SITE, APPLICATION, SERVICES, COLLECTIVE CONTENT, INCLUDING, BUT NOT LIMITED TO, THE LISTINGS OR THE REFERRAL PROGRAM WILL MEET YOUR REQUIREMENTS OR BE AVAILABLE ON AN UNINTERRUPTED, SECURE, OR ERROR-FREE BASIS. EVEROFFER MAKES NO WARRANTY REGARDING THE QUALITY OF ANY LISTINGS, THE SERVICES OR COLLECTIVE CONTENT OR THE ACCURACY, TIMELINESS, TRUTHFULNESS, COMPLETENESS OR RELIABILITY OF ANY COLLECTIVE CONTENT OBTAINED THROUGH THE SITE, APPLICATION, SERVICES OR REFERRAL PROGRAM.</p>

<p>NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM EVEROFFER OR THROUGH THE SITE, APPLICATION, SERVICES OR COLLECTIVE CONTENT, WILL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN.</p>

<p>YOU ARE SOLELY RESPONSIBLE FOR ALL OF YOUR COMMUNICATIONS AND INTERACTIONS WITH OTHER USERS OF THE SITE, APPLICATION OR SERVICES AND WITH OTHER PERSONS WITH WHOM YOU COMMUNICATE OR INTERACT AS A RESULT OF YOUR USE OF THE SITE, APPLICATION OR SERVICES, INCLUDING, BUT NOT LIMITED TO, ANY MERCHANT OR COUSTOMER. YOU UNDERSTAND THAT EVEROFFER DOES NOT MAKE ANY ATTEMPT TO VERIFY THE STATEMENTS OF USERS OF THE SITE, APPLICATION OR SERVICES OR TO REVIEW THE QUALITY OF PRODUCT OR SERVICES. EVEROFFER MAKES NO REPRESENTATIONS OR WARRANTIES AS TO THE CONDUCT OF USERS OF THE SITE, APPLICATION OR SERVICES OR THEIR COMPATIBILITY WITH ANY CURRENT OR FUTURE USERS OF THE SITE, APPLICATION OR SERVICES. YOU AGREE TO TAKE REASONABLE PRECAUTIONS IN ALL COMMUNICATIONS AND INTERACTIONS WITH OTHER USERS OF THE SITE, APPLICATION OR SERVICES AND WITH OTHER PERSONS WITH WHOM YOU COMMUNICATE OR INTERACT AS A RESULT OF YOUR USE OF THE SITE, APPLICATION OR SERVICES, INCLUDING, BUT NOT LIMITED TO, COSTOMER  AND MERCHANT, PARTICULARLY IF YOU DECIDE TO MEET OFFLINE OR IN PERSON.</p>
	<h4>Indemnification</h4>
    <p>You agree to release, defend, indemnify, and hold EVEROFFER and its affiliates and subsidiaries, and their officers, directors, employees and agents, harmless from and against any claims, liabilities, damages, losses, and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected with (a) your access to or use of the Site, Application, Services, or Collective Content or your violation of these Terms; (b) your Member Content; (c) your (i) interaction with any Member, (ii) PURCHESING OF PRODUCT OR SERVICES (iii) creation of a Listing or (iv) the use, condition of PRODUCT OR SERVICES, including, but not limited to any injuries, losses, or damages (compensatory, direct, incidental, consequential or otherwise) of any kind arising in connection with or as a result of a USE OF PRODUCT OR AVAIL SERVICE </p>	
    <h4>Entire Agreement</h4>
    <p>These Terms constitute the entire and exclusive understanding and agreement between EVEROFFER and you regarding the Site, Application, Services, Collective Content, Referral Program, via the Site, Application and Services, and these Terms supersede and replace any and all prior oral or written understandings or agreements between EVEROFFER and you regarding the Site, Application, Services, Collective Content and Referral Program.</p>
    <br>
    <h4>Assignment</h4>
    <p>You may not assign or transfer these Terms, by operation of law or otherwise, without EVEROFFER's prior written consent. Any attempt by you to assign or transfer these Terms, without such consent, will be null and of no effect. EVEROFFER may assign or transfer these Terms, at its sole discretion, without restriction. Subject to the foregoing, these Terms will bind and inure to the benefit of the parties, their successors and permitted assigns.</p>
    <br>
    <h4>Notices</h4>
    <p>Any notices or other communications permitted or required hereunder, including those regarding modifications to these Terms, will be in writing and given by EVEROFFER (i) via email (in each case to the address that you provide) or (ii) by posting to the Site or via the Application. For notices made by e-mail, the date of receipt will be deemed the date on which such notice is transmitted.</p>
    <br>
    <h4>Controlling Law and Jurisdiction</h4>
    <p>These Terms will be interpreted in accordance with the laws of the India. You and we agree to submit to the exclusive jurisdiction of a court located in Washim District, Maharashtra, India for any dispute, claim or actions in relation to these Terms or the use of services provided through www.everoffer.in.</p>
    <br>
    <h4>General</h4>
    <p>The failure of EVEROFFER to enforce any right or provision of these Terms will not constitute a waiver of future enforcement of that right or provision. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of EVEROFFER. Except as expressly set forth in these Terms, the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies under these Terms or otherwise. If for any reason an arbitrator or a court of competent jurisdiction finds any provision of these Terms invalid or unenforceable, that provision will be enforced to the maximum extent permissible and the other provisions of these Terms will remain in full force and effect.</p>
    <br>
    <h4>Contacting EverOffer</h4>
    <p>If you have any questions about these Terms or any App Store Sourced Application, please contact EVEROFFER at info@everoffer.com</p>
	</div>
</div>
<!--//contact-->
</body>
</html>