package com.ever.offer.in.model;

// Generated 23 Nov, 2015 5:58:55 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address")
public class Address extends AbstractEntity implements java.io.Serializable {

    private City city;
    private String addressFirst;
    private String addressSecond;
    private String addressThird;
    private String contactNo;
    private String contactEmail;
    private Integer pinCode;
    private String contactUrl;
    private String letitude;
    private String longitude;
    private State state;
    private String image;
    private String password;

    public Address() {
    }

    public Address(City city, String addressFirst, String addressSecond, String addressThird, String contactNo,
                    String contactEmail, Integer pinCode, String contactUrl, String letitude, String longitude,String image,String password) {
        this.city = city;
        this.addressFirst = addressFirst;
        this.addressSecond = addressSecond;
        this.addressThird = addressThird;
        this.contactNo = contactNo;
        this.contactEmail = contactEmail;
        this.pinCode = pinCode;
        this.contactUrl = contactUrl;
        this.letitude = letitude;
        this.longitude = longitude;
        this.image=image;
        this.password=password;
    }

    @JsonIgnore
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "city_id")
    public City getCity() {
        return this.city;
    }

    public void setCity(City city) {
        this.city = city;
    }

    @Column(name = "address_first", length = 55)
    public String getAddressFirst() {
        return this.addressFirst;
    }

    public void setAddressFirst(String addressFirst) {
        this.addressFirst = addressFirst;
    }

    @Column(name = "address_second", length = 55)
    public String getAddressSecond() {
        return this.addressSecond;
    }

    public void setAddressSecond(String addressSecond) {
        this.addressSecond = addressSecond;
    }

    @Column(name = "address_third", length = 55)
    public String getAddressThird() {
        return this.addressThird;
    }

    public void setAddressThird(String addressThird) {
        this.addressThird = addressThird;
    }

    @Column(name = "contact_no", length = 25)
    public String getContactNo() {
        return this.contactNo;
    }

    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

    @Column(name = "contact_email", length = 55)
    public String getContactEmail() {
        return this.contactEmail;
    }

    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }

    @Column(name = "pin_code")
    public Integer getPinCode() {
        return this.pinCode;
    }

    public void setPinCode(Integer pinCode) {
        this.pinCode = pinCode;
    }

    @Column(name = "contact_url", length = 55)
    public String getContactUrl() {
        return this.contactUrl;
    }

    public void setContactUrl(String contactUrl) {
        this.contactUrl = contactUrl;
    }

    @Column(name = "letitude", length = 55)
    public String getLetitude() {
        return letitude;
    }

    public void setLetitude(String letitude) {
        this.letitude = letitude;
    }

    @Column(name = "longitude", length = 55)
    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    @JsonIgnore
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "state_id")
    public State getState() {
        return state;
    }

    public void setState(State state) {
        this.state = state;
    }

    @Transient
    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    @Transient
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
