package com.ever.offer.in.model;

// Generated 23 Nov, 2015 5:58:55 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city")
public class City extends AbstractEntity implements java.io.Serializable {

    private State state;
    private String cityName;
    private String letitude;
    private String longitude;

    public City() {
    }

    public City(State state, String cityName) {
        this.state = state;
        this.cityName = cityName;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "state_id")
    public State getState() {
        return this.state;
    }

    public void setState(State state) {
        this.state = state;
    }

    @Column(name = "city_name", length = 55)
    public String getCityName() {
        return this.cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    @Transient
    public String getLetitude() {
        return letitude;
    }

    public void setLetitude(String letitude) {
        this.letitude = letitude;
    }

    @Transient
    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }
}
