package com.ever.offer.in.model;

// Generated 23 Nov, 2015 5:58:55 PM by Hibernate Tools 4.3.1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name = "login")
public class Login extends AbstractEntity implements java.io.Serializable {

	private Address address;
	private Role role;
	private String userName;
	private String password;
	private String name;
	private String timePeriod;
	private String openingTime;
	private String closingTime;
	private Integer merchantType;
	private String termCondition;
	private String complementry;
	private String complemenrtCheck;
	private String contact;
	private String image;
	private Payment payment;
	private Integer subscriptionPlan;
	private Integer registrationType;
	private Integer isApproved;
	private Employee employee;
	private Integer type;
	private String otpCode;
	private Integer count;
	private Integer amount;
	private String fieldOfficer;
	private String supervisior;
	private String manager;
	private String emailId;
	private String empAddress;

	public Login() {
	}

	public Login(Address address, Role role, String userName, String password, String name, String openingTime,
					String closingTime, Integer merchantType, String termCondition, String timePeriod,
					String complementry, String image, Payment payment, Integer subscriptionPlan,
					Integer registrationType, Employee employee, Integer type, String otpCode, Integer amount,
					Integer count, String fieldOfficer, String supervisior, String manager, String emailId,
					String empAddress) {
		this.address = address;
		this.role = role;
		this.userName = userName;
		this.password = password;
		this.name = name;
		this.timePeriod = timePeriod;
		this.openingTime = openingTime;
		this.closingTime = closingTime;
		this.merchantType = merchantType;
		this.termCondition = termCondition;
		this.complementry = complementry;
		this.image = image;
		this.payment = payment;
		this.subscriptionPlan = subscriptionPlan;
		this.registrationType = registrationType;
		this.employee = employee;
		this.type = type;
		this.otpCode = otpCode;
		this.count = count;
		this.amount = amount;
		this.fieldOfficer = fieldOfficer;
		this.supervisior = supervisior;
		this.emailId = emailId;
		this.manager = manager;
		this.empAddress = empAddress;
	}

	@javax.persistence.Transient
	public String getComplementry() {
		return complementry;
	}

	public void setComplementry(String complementry) {
		this.complementry = complementry;
	}

	@Column(name = "time_period", length = 11)
	public String getTimePeriod() {
		return timePeriod;
	}

	public void setTimePeriod(String timePeriod) {
		this.timePeriod = timePeriod;
	}

	@ManyToOne(cascade = CascadeType.ALL)
	/* (fetch = FetchType.LAZY) */
	@JoinColumn(name = "address_id", referencedColumnName = "id")
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "role_id", referencedColumnName = "id")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "user_name", length = 55)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", length = 55)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "name", length = 55)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "opening_time", length = 55)
	public String getOpeningTime() {
		return this.openingTime;
	}

	public void setOpeningTime(String openingTime) {
		this.openingTime = openingTime;
	}

	@Column(name = "closing_time", length = 55)
	public String getClosingTime() {
		return this.closingTime;
	}

	public void setClosingTime(String closingTime) {
		this.closingTime = closingTime;
	}

	@Column(name = "merchant_type", length = 2)
	public Integer getMerchantType() {
		return merchantType;
	}

	public void setMerchantType(Integer merchantType) {
		this.merchantType = merchantType;
	}

	@Column(name = "term_condition", length = 5)
	public String getTermCondition() {
		return termCondition;
	}

	public void setTermCondition(String termCondition) {
		this.termCondition = termCondition;
	}

	@Transient
	public String getComplemenrtCheck() {
		return complemenrtCheck;
	}

	public void setComplemenrtCheck(String complemenrtCheck) {
		this.complemenrtCheck = complemenrtCheck;
	}

	@Transient
	public String getContact() {
		return contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "image")
	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "payment_id", referencedColumnName = "id")
	public Payment getPayment() {
		return payment;
	}

	public void setPayment(Payment payment) {
		this.payment = payment;
	}

	@Column(name = "subscription_plan")
	public Integer getSubscriptionPlan() {
		return subscriptionPlan;
	}

	public void setSubscriptionPlan(Integer subscriptionPlan) {
		this.subscriptionPlan = subscriptionPlan;
	}

	@Transient
	public Integer getRegistrationType() {
		return registrationType;
	}

	public void setRegistrationType(Integer registrationType) {
		this.registrationType = registrationType;
	}

	@Column(name = "isApproved")
	public Integer getIsApproved() {
		return isApproved;
	}

	public void setIsApproved(Integer isApproved) {
		this.isApproved = isApproved;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "employee_id")
	public Employee getEmployee() {
		return employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Transient
	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "opt_code")
	public String getOtpCode() {
		return otpCode;
	}

	public void setOtpCode(String otpCode) {
		this.otpCode = otpCode;
	}

	@Transient
	public Integer getCount() {
		return count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Transient
	public Integer getAmount() {
		return amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	@Transient
	public String getFieldOfficer() {
		return fieldOfficer;
	}

	public void setFieldOfficer(String fieldOfficer) {
		this.fieldOfficer = fieldOfficer;
	}

	@Transient
	public String getSupervisior() {
		return supervisior;
	}

	public void setSupervisior(String supervisior) {
		this.supervisior = supervisior;
	}

	@Transient
	public String getManager() {
		return manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	@Transient
	public String getEmailId() {
		return emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Transient
	public String getEmpAddress() {
		return empAddress;
	}

	public void setEmpAddress(String empAddress) {
		this.empAddress = empAddress;
	}

}
