package com.ever.offer.in.model;

// Generated 23 Nov, 2015 5:58:55 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Offer generated by hbm2java
 */
@Entity
@Table(name = "offer")
public class Offer extends AbstractEntity implements java.io.Serializable {

    private Login login;
    private String offerDescription;
    private String offerStartTime;
    private String offerEndTime;
    private String offerValidity;
    private String offerCoupanCode;
    private String offerHeading;
    private String termsAndConditions;
    private int isApproved;
    private int noOfCouponsPerPerson;
    private String image;
    private int normalPrice;
    private int offerPrice;
    private int rateType;
    private int rateValue;

    public Offer() {
    }

    public Offer(Login login, String offerDescription, String offerStartTime, String offerEndTime,
                    String offerCoupanCode, String offerHeading, int isApproved, String offerValidity,
                    String termsAndConditions, int noOfCouponsPerPerson, String image, int normalPrice, int offerPrice,
                    int rateType, int rateValue) {
        this.login = login;
        this.offerDescription = offerDescription;
        this.offerStartTime = offerStartTime;
        this.offerEndTime = offerEndTime;
        this.offerValidity = offerValidity;
        this.offerCoupanCode = offerCoupanCode;
        this.offerHeading = offerHeading;
        this.setTermsAndConditions(termsAndConditions);
        this.isApproved = isApproved;
        this.noOfCouponsPerPerson = noOfCouponsPerPerson;
        this.image = image;
        this.normalPrice = normalPrice;
        this.offerPrice = offerPrice;
        this.rateType = rateType;
        this.rateValue = rateValue;
    }

    @Column(name = "rate_type", length = 55)
    public int getRateType() {
        return rateType;
    }

    public void setRateType(int rateType) {
        this.rateType = rateType;
    }

    @Column(name = "rate_value", length = 55)
    public int getRateValue() {
        return rateValue;
    }

    public void setRateValue(int rateValue) {
        this.rateValue = rateValue;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "login_id")
    public Login getLogin() {
        return this.login;
    }

    public void setLogin(Login login) {
        this.login = login;
    }

    @Column(name = "offer_description", length = 250)
    public String getOfferDescription() {
        return this.offerDescription;
    }

    public void setOfferDescription(String offerDescription) {
        this.offerDescription = offerDescription;
    }

    @Column(name = "offer_start_time", length = 55)
    public String getOfferStartTime() {
        return this.offerStartTime;
    }

    public void setOfferStartTime(String offerStartTime) {
        this.offerStartTime = offerStartTime;
    }

    @Column(name = "offer_end_time", length = 55)
    public String getOfferEndTime() {
        return this.offerEndTime;
    }

    public void setOfferEndTime(String offerEndTime) {
        this.offerEndTime = offerEndTime;
    }

    @Column(name = "offer_validity", length = 55)
    public String getOfferValidity() {
        return offerValidity;
    }

    public void setOfferValidity(String offerValidity) {
        this.offerValidity = offerValidity;
    }

    @Column(name = "offer_coupan_code", length = 55)
    public String getOfferCoupanCode() {
        return this.offerCoupanCode;
    }

    public void setOfferCoupanCode(String offerCoupanCode) {
        this.offerCoupanCode = offerCoupanCode;
    }

    @Column(name = "offer_heading", length = 250)
    public String getOfferHeading() {
        return this.offerHeading;
    }

    public void setOfferHeading(String offerHeading) {
        this.offerHeading = offerHeading;
    }

    @Column(name = "terms_and_conditions", length = 250)
    public String getTermsAndConditions() {
        return termsAndConditions;
    }

    @Column(name = "is_approved")
    public int getIsApproved() {
        return isApproved;
    }

    public void setIsApproved(int isApproved) {
        this.isApproved = isApproved;
    }

    public void setTermsAndConditions(String termsAndConditions) {
        this.termsAndConditions = termsAndConditions;
    }

    @Column(name = "no_of_coupons_per_person")
    public int getNoOfCouponsPerPerson() {
        return noOfCouponsPerPerson;
    }

    public void setNoOfCouponsPerPerson(int noOfCouponsPerPerson) {
        this.noOfCouponsPerPerson = noOfCouponsPerPerson;
    }

    @Column(name = "image")
    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    @Column(name = "normal_price")
    public int getNormalPrice() {
        return normalPrice;
    }

    public void setNormalPrice(int normalPrice) {
        this.normalPrice = normalPrice;
    }

    @Column(name = "offer_price")
    public int getOfferPrice() {
        return offerPrice;
    }

    public void setOfferPrice(int offerPrice) {
        this.offerPrice = offerPrice;
    }

}
