package com.ever.offer.in.model;

// Generated 23 Nov, 2015 5:58:55 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role")
public class Role extends AbstractEntity implements java.io.Serializable {

    private String roleType;

    public Role() {
    }

    public Role(String roleType) {
        this.roleType = roleType;
    }

    @Column(name = "role_type", length = 55)
    public String getRoleType() {
        return this.roleType;
    }

    public void setRoleType(String roleType) {
        this.roleType = roleType;
    }
}
